version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      # 環境変数の設定
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - REGION=${REGION}
      - ECR_REPOSITORY_URL=${ECR_REPOSITORY_URL}
      # コミットハッシュの先頭7桁をタグに利用する
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      # ECRログイン
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build ./docker -t $ECR_REPOSITORY_URL:latest
      - docker tag $ECR_REPOSITORY_URL:latest $ECR_REPOSITORY_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_REPOSITORY_URL:latest
      - docker push $ECR_REPOSITORY_URL:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $ECR_REPOSITORY_URL:$IMAGE_TAG > imageDetail.json
      - echo Rewriting task definitions file...
      - sed -i -e "s#<project>#$project#g" module/codebuild/taskdef.json
      - sed -i -e "s#<env>#$env#g" module/codebuild/taskdef.json
      - sed -i -e "s#<task_role>#$task_role#g" module/codebuild/taskdef.json
      - sed -i -e "s#<execution_role_arn>#$execution_role_arn#g" module/codebuild/taskdef.json
      - cp module/codebuild/taskdef.json ./
      - echo Finished Rewriting task definitions file
      - echo Rewriting appspec file...
      - sed -i -e "s#<project>#$project#g" module/codebuild/appspec.yml
      - sed -i -e "s#<env>#$env#g" module/codebuild/appspec.yml
      - sed -i -e "s#<task_role>#$task_role#g" module/codebuild/appspec.yml
      - echo Finished Rewriting appspec file
      - cp module/codebuild/appspec.yml ./
artifacts:
    files: 
      - imageDetail.json
      - taskdef.json
      - appspec.yml
